server:
  port: 8088

spring:
  application:
    name: Quick_Mapping
    version: 1.0
  jackson:
    default-property-inclusion: non_default
  servlet:
    multipart:
      max-file-size: 500MB

docs:
  api: https://console-docs.apipost.cn/preview/06757b13ae429b20/ae205ac0d0229893
  github: https://github.com/chuanq118/quick_mapping